// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'core/services/env_service.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: EnvService.firebaseWebApiKey,
    appId: EnvService.firebaseWebAppId,
    messagingSenderId: EnvService.firebaseWebMessagingSenderId,
    projectId: EnvService.firebaseProjectId,
    authDomain: EnvService.firebaseWebAuthDomain,
    storageBucket: EnvService.firebaseWebStorageBucket,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: EnvService.firebaseAndroidApiKey,
    appId: EnvService.firebaseAndroidAppId,
    messagingSenderId: EnvService.firebaseAndroidMessagingSenderId,
    projectId: EnvService.firebaseProjectId,
    storageBucket: EnvService.firebaseAndroidStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: EnvService.firebaseIosApiKey,
    appId: EnvService.firebaseIosAppId,
    messagingSenderId: EnvService.firebaseIosMessagingSenderId,
    projectId: EnvService.firebaseProjectId,
    storageBucket: EnvService.firebaseIosStorageBucket,
    iosBundleId: EnvService.firebaseIosBundleId,
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: EnvService.firebaseMacosApiKey,
    appId: EnvService.firebaseMacosAppId,
    messagingSenderId: EnvService.firebaseMacosMessagingSenderId,
    projectId: EnvService.firebaseProjectId,
    storageBucket: EnvService.firebaseMacosStorageBucket,
    iosBundleId: EnvService.firebaseMacosBundleId,
  );
}
