// Mocks generated by Mockito 5.4.6 from annotations
// in ed_wise/test/unit/bloc/ai_video_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ed_wise/core/repositories/ai_video_repository.dart' as _i3;
import 'package:ed_wise/features/ai_video/models/ai_video.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAiVideo_0 extends _i1.SmartFake implements _i2.AiVideo {
  _FakeAiVideo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiVideoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiVideoRepository extends _i1.Mock implements _i3.AiVideoRepository {
  MockAiVideoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.AiVideo>> getVideos(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [userId]),
            returnValue: _i4.Future<List<_i2.AiVideo>>.value(<_i2.AiVideo>[]),
          )
          as _i4.Future<List<_i2.AiVideo>>);

  @override
  _i4.Future<_i2.AiVideo> createVideo(
    _i2.VideoGenerationRequest? request,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createVideo, [request, userId]),
            returnValue: _i4.Future<_i2.AiVideo>.value(
              _FakeAiVideo_0(
                this,
                Invocation.method(#createVideo, [request, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.AiVideo>);
}
