// Mocks generated by Mockito 5.4.6 from annotations
// in ed_wise/test/unit/bloc/certificate_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ed_wise/core/repositories/certificate_repository.dart' as _i3;
import 'package:ed_wise/features/profile/models/certificate.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCertificate_0 extends _i1.SmartFake implements _i2.Certificate {
  _FakeCertificate_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CertificateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCertificateRepository extends _i1.Mock
    implements _i3.CertificateRepository {
  MockCertificateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Certificate>> getCertificates(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCertificates, [userId]),
            returnValue: _i4.Future<List<_i2.Certificate>>.value(
              <_i2.Certificate>[],
            ),
          )
          as _i4.Future<List<_i2.Certificate>>);

  @override
  _i4.Future<_i2.Certificate> generateCertificate({
    required String? userId,
    required String? courseName,
    required String? title,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateCertificate, [], {
              #userId: userId,
              #courseName: courseName,
              #title: title,
              #description: description,
            }),
            returnValue: _i4.Future<_i2.Certificate>.value(
              _FakeCertificate_0(
                this,
                Invocation.method(#generateCertificate, [], {
                  #userId: userId,
                  #courseName: courseName,
                  #title: title,
                  #description: description,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Certificate>);

  @override
  _i4.Future<String> downloadCertificate(_i2.Certificate? certificate) =>
      (super.noSuchMethod(
            Invocation.method(#downloadCertificate, [certificate]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#downloadCertificate, [certificate]),
              ),
            ),
          )
          as _i4.Future<String>);
}
