// Mocks generated by Mockito 5.4.6 from annotations
// in ed_wise/test/unit/bloc/comment_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ed_wise/core/repositories/comment_repository.dart' as _i3;
import 'package:ed_wise/features/forum/models/forum_post.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForumComment_0 extends _i1.SmartFake implements _i2.ForumComment {
  _FakeForumComment_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CommentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentRepository extends _i1.Mock implements _i3.CommentRepository {
  MockCommentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ForumComment>> getComments(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postId]),
            returnValue: _i4.Future<List<_i2.ForumComment>>.value(
              <_i2.ForumComment>[],
            ),
          )
          as _i4.Future<List<_i2.ForumComment>>);

  @override
  _i4.Future<_i2.ForumComment> createComment({
    required String? postId,
    required String? userId,
    required String? userName,
    required String? userEmail,
    required String? content,
    String? parentCommentId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #userId: userId,
              #userName: userName,
              #userEmail: userEmail,
              #content: content,
              #parentCommentId: parentCommentId,
            }),
            returnValue: _i4.Future<_i2.ForumComment>.value(
              _FakeForumComment_0(
                this,
                Invocation.method(#createComment, [], {
                  #postId: postId,
                  #userId: userId,
                  #userName: userName,
                  #userEmail: userEmail,
                  #content: content,
                  #parentCommentId: parentCommentId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ForumComment>);

  @override
  _i4.Future<void> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upvoteComment(String? commentId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#upvoteComment, [commentId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> downvoteComment(String? commentId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#downvoteComment, [commentId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
