// Mocks generated by Mockito 5.4.6 from annotations
// in ed_wise/test/unit/bloc/forum_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ed_wise/core/repositories/forum_repository.dart' as _i3;
import 'package:ed_wise/features/forum/models/forum_post.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeForumPost_0 extends _i1.SmartFake implements _i2.ForumPost {
  _FakeForumPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForumRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForumRepository extends _i1.Mock implements _i3.ForumRepository {
  MockForumRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ForumPost>> getPosts({String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [], {#category: category}),
            returnValue: _i4.Future<List<_i2.ForumPost>>.value(
              <_i2.ForumPost>[],
            ),
          )
          as _i4.Future<List<_i2.ForumPost>>);

  @override
  _i4.Future<_i2.ForumPost> createPost({
    required String? userId,
    required String? userName,
    required String? userEmail,
    required String? title,
    required String? content,
    required String? category,
    required List<String>? tags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #userId: userId,
              #userName: userName,
              #userEmail: userEmail,
              #title: title,
              #content: content,
              #category: category,
              #tags: tags,
            }),
            returnValue: _i4.Future<_i2.ForumPost>.value(
              _FakeForumPost_0(
                this,
                Invocation.method(#createPost, [], {
                  #userId: userId,
                  #userName: userName,
                  #userEmail: userEmail,
                  #title: title,
                  #content: content,
                  #category: category,
                  #tags: tags,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<void> updatePost(String? postId, Map<String, dynamic>? updates) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [postId, updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> upvotePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#upvotePost, [postId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> downvotePost(String? postId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#downvotePost, [postId, userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
